# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Applied Programming in R for Natural Sciences
description:      'Teaching the tools to use R to do cool science'
url:              https://jpomz.github.io/ENVS318/
baseurl:          /ENVS318
email:            jpomeranz@coloradomesa.edu
feedbackurl:      
author:
  name:           'Justin Pomeranz'
  url:            

github:
  repo:           https://github.com/Jpomz/ENVS318-Applied-R-NatSci.git
  #               Be sure the 'Issues' feature is activated in 'Settings'

plugins:
  - jekyll-sitemap